// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: rag.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Query     string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	SessionId string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// 🔥 v0.4.0 核心新增：多租户过滤器
	// 如果传了 kb_id，只在这个知识库搜
	// 如果没传 kb_id 但传了 org_id，在该组织下所有库搜
	OrgId int64 `protobuf:"varint,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	KbId  int64 `protobuf:"varint,4,opt,name=kb_id,json=kbId,proto3" json:"kb_id,omitempty"`
	// 历史记录 (可选，简化版)
	History       []*Message `protobuf:"bytes,5,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_rag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ChatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatRequest) GetOrgId() int64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

func (x *ChatRequest) GetKbId() int64 {
	if x != nil {
		return x.KbId
	}
	return 0
}

func (x *ChatRequest) GetHistory() []*Message {
	if x != nil {
		return x.History
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // "user" or "assistant"
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_rag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ChatReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnswerDelta   string                 `protobuf:"bytes,1,opt,name=answer_delta,json=answerDelta,proto3" json:"answer_delta,omitempty"` // 流式生成的文本片段
	SourceDocs    string                 `protobuf:"bytes,2,opt,name=source_docs,json=sourceDocs,proto3" json:"source_docs,omitempty"`    // 引用来源 (JSON 字符串或格式化文本)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatReply) Reset() {
	*x = ChatReply{}
	mi := &file_rag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatReply) ProtoMessage() {}

func (x *ChatReply) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatReply.ProtoReflect.Descriptor instead.
func (*ChatReply) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{2}
}

func (x *ChatReply) GetAnswerDelta() string {
	if x != nil {
		return x.AnswerDelta
	}
	return ""
}

func (x *ChatReply) GetSourceDocs() string {
	if x != nil {
		return x.SourceDocs
	}
	return ""
}

type ParseRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 🔥 变更 1: 传 MinIO 路径，而不是文件内容
	// 例如: "kbs/1/uuid.pdf"
	StoragePath string `protobuf:"bytes,1,opt,name=storage_path,json=storagePath,proto3" json:"storage_path,omitempty"`
	FileName    string `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	// 🔥 变更 2: 传递元数据，用于 Python 写入 Qdrant Payload
	KbId          int64 `protobuf:"varint,3,opt,name=kb_id,json=kbId,proto3" json:"kb_id,omitempty"`
	DocId         int64 `protobuf:"varint,4,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	OrgId         int64 `protobuf:"varint,5,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"` // 如果是个人库，这里传 0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseRequest) Reset() {
	*x = ParseRequest{}
	mi := &file_rag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseRequest) ProtoMessage() {}

func (x *ParseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseRequest.ProtoReflect.Descriptor instead.
func (*ParseRequest) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{3}
}

func (x *ParseRequest) GetStoragePath() string {
	if x != nil {
		return x.StoragePath
	}
	return ""
}

func (x *ParseRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ParseRequest) GetKbId() int64 {
	if x != nil {
		return x.KbId
	}
	return 0
}

func (x *ParseRequest) GetDocId() int64 {
	if x != nil {
		return x.DocId
	}
	return 0
}

func (x *ParseRequest) GetOrgId() int64 {
	if x != nil {
		return x.OrgId
	}
	return 0
}

type ParseResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Success  bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMsg string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	// 🔥 变更 3: 只返回统计数据，不返回向量
	ChunkCount    int32 `protobuf:"varint,3,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"` // 切了多少片
	PageCount     int32 `protobuf:"varint,4,opt,name=page_count,json=pageCount,proto3" json:"page_count,omitempty"`    // 总页数 (Docling 解析结果)
	TokenUsage    int32 `protobuf:"varint,5,opt,name=token_usage,json=tokenUsage,proto3" json:"token_usage,omitempty"` // 消耗 Token 数 (可选)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseResponse) Reset() {
	*x = ParseResponse{}
	mi := &file_rag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseResponse) ProtoMessage() {}

func (x *ParseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseResponse.ProtoReflect.Descriptor instead.
func (*ParseResponse) Descriptor() ([]byte, []int) {
	return file_rag_proto_rawDescGZIP(), []int{4}
}

func (x *ParseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ParseResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *ParseResponse) GetChunkCount() int32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

func (x *ParseResponse) GetPageCount() int32 {
	if x != nil {
		return x.PageCount
	}
	return 0
}

func (x *ParseResponse) GetTokenUsage() int32 {
	if x != nil {
		return x.TokenUsage
	}
	return 0
}

var File_rag_proto protoreflect.FileDescriptor

const file_rag_proto_rawDesc = "" +
	"\n" +
	"\trag.proto\x12\x06rag.v1\"\x99\x01\n" +
	"\vChatRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\x03R\x05orgId\x12\x13\n" +
	"\x05kb_id\x18\x04 \x01(\x03R\x04kbId\x12)\n" +
	"\ahistory\x18\x05 \x03(\v2\x0f.rag.v1.MessageR\ahistory\"7\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"O\n" +
	"\tChatReply\x12!\n" +
	"\fanswer_delta\x18\x01 \x01(\tR\vanswerDelta\x12\x1f\n" +
	"\vsource_docs\x18\x02 \x01(\tR\n" +
	"sourceDocs\"\x91\x01\n" +
	"\fParseRequest\x12!\n" +
	"\fstorage_path\x18\x01 \x01(\tR\vstoragePath\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x13\n" +
	"\x05kb_id\x18\x03 \x01(\x03R\x04kbId\x12\x15\n" +
	"\x06doc_id\x18\x04 \x01(\x03R\x05docId\x12\x15\n" +
	"\x06org_id\x18\x05 \x01(\x03R\x05orgId\"\xa7\x01\n" +
	"\rParseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x12\x1f\n" +
	"\vchunk_count\x18\x03 \x01(\x05R\n" +
	"chunkCount\x12\x1d\n" +
	"\n" +
	"page_count\x18\x04 \x01(\x05R\tpageCount\x12\x1f\n" +
	"\vtoken_usage\x18\x05 \x01(\x05R\n" +
	"tokenUsage2\x87\x01\n" +
	"\n" +
	"RagService\x128\n" +
	"\n" +
	"ChatStream\x12\x13.rag.v1.ChatRequest\x1a\x11.rag.v1.ChatReply\"\x000\x01\x12?\n" +
	"\x0eParseAndIngest\x12\x14.rag.v1.ParseRequest\x1a\x15.rag.v1.ParseResponse\"\x00B\x1bZ\x19Chimera-RAG/api/rag/v1;v1b\x06proto3"

var (
	file_rag_proto_rawDescOnce sync.Once
	file_rag_proto_rawDescData []byte
)

func file_rag_proto_rawDescGZIP() []byte {
	file_rag_proto_rawDescOnce.Do(func() {
		file_rag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rag_proto_rawDesc), len(file_rag_proto_rawDesc)))
	})
	return file_rag_proto_rawDescData
}

var file_rag_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_rag_proto_goTypes = []any{
	(*ChatRequest)(nil),   // 0: rag.v1.ChatRequest
	(*Message)(nil),       // 1: rag.v1.Message
	(*ChatReply)(nil),     // 2: rag.v1.ChatReply
	(*ParseRequest)(nil),  // 3: rag.v1.ParseRequest
	(*ParseResponse)(nil), // 4: rag.v1.ParseResponse
}
var file_rag_proto_depIdxs = []int32{
	1, // 0: rag.v1.ChatRequest.history:type_name -> rag.v1.Message
	0, // 1: rag.v1.RagService.ChatStream:input_type -> rag.v1.ChatRequest
	3, // 2: rag.v1.RagService.ParseAndIngest:input_type -> rag.v1.ParseRequest
	2, // 3: rag.v1.RagService.ChatStream:output_type -> rag.v1.ChatReply
	4, // 4: rag.v1.RagService.ParseAndIngest:output_type -> rag.v1.ParseResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rag_proto_init() }
func file_rag_proto_init() {
	if File_rag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rag_proto_rawDesc), len(file_rag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rag_proto_goTypes,
		DependencyIndexes: file_rag_proto_depIdxs,
		MessageInfos:      file_rag_proto_msgTypes,
	}.Build()
	File_rag_proto = out.File
	file_rag_proto_goTypes = nil
	file_rag_proto_depIdxs = nil
}
