// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: api/runtime/v1/runtime.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AppConfigJson string                 `protobuf:"bytes,4,opt,name=app_config_json,json=appConfigJson,proto3" json:"app_config_json,omitempty"`
	History       []*Message             `protobuf:"bytes,5,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunAgentRequest) Reset() {
	*x = RunAgentRequest{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunAgentRequest) ProtoMessage() {}

func (x *RunAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunAgentRequest.ProtoReflect.Descriptor instead.
func (*RunAgentRequest) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *RunAgentRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *RunAgentRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RunAgentRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RunAgentRequest) GetAppConfigJson() string {
	if x != nil {
		return x.AppConfigJson
	}
	return ""
}

func (x *RunAgentRequest) GetHistory() []*Message {
	if x != nil {
		return x.History
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type RunAgentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type: "thought" | "delta" | "reference" | "error" | "summary"
	Type    string     `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Payload string     `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Meta    *AgentMeta `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	// 🔥 新增：执行摘要 (仅在 type="summary" 时存在，且作为流的最后一帧)
	Summary       *RunSummary `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunAgentResponse) Reset() {
	*x = RunAgentResponse{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunAgentResponse) ProtoMessage() {}

func (x *RunAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunAgentResponse.ProtoReflect.Descriptor instead.
func (*RunAgentResponse) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *RunAgentResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RunAgentResponse) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *RunAgentResponse) GetMeta() *AgentMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *RunAgentResponse) GetSummary() *RunSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

type AgentMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	DurationMs    int64                  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMeta) Reset() {
	*x = AgentMeta{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMeta) ProtoMessage() {}

func (x *AgentMeta) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMeta.ProtoReflect.Descriptor instead.
func (*AgentMeta) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *AgentMeta) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *AgentMeta) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *AgentMeta) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

// 🔥 新增：统计数据结构
type RunSummary struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalTokens      int32                  `protobuf:"varint,1,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	PromptTokens     int32                  `protobuf:"varint,2,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int32                  `protobuf:"varint,3,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalDurationMs  int64                  `protobuf:"varint,4,opt,name=total_duration_ms,json=totalDurationMs,proto3" json:"total_duration_ms,omitempty"` // Python 侧计算的总耗时
	FinalStatus      string                 `protobuf:"bytes,5,opt,name=final_status,json=finalStatus,proto3" json:"final_status,omitempty"`                // "success" | "failed"
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RunSummary) Reset() {
	*x = RunSummary{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunSummary) ProtoMessage() {}

func (x *RunSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunSummary.ProtoReflect.Descriptor instead.
func (*RunSummary) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{4}
}

func (x *RunSummary) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *RunSummary) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *RunSummary) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *RunSummary) GetTotalDurationMs() int64 {
	if x != nil {
		return x.TotalDurationMs
	}
	return 0
}

func (x *RunSummary) GetFinalStatus() string {
	if x != nil {
		return x.FinalStatus
	}
	return ""
}

// --- ETL 相关 (保持不变) ---
type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KbId          int64                  `protobuf:"varint,1,opt,name=kb_id,json=kbId,proto3" json:"kb_id,omitempty"`
	DatasourceId  int64                  `protobuf:"varint,2,opt,name=datasource_id,json=datasourceId,proto3" json:"datasource_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	ConfigJson    string                 `protobuf:"bytes,4,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{5}
}

func (x *SyncRequest) GetKbId() int64 {
	if x != nil {
		return x.KbId
	}
	return 0
}

func (x *SyncRequest) GetDatasourceId() int64 {
	if x != nil {
		return x.DatasourceId
	}
	return 0
}

func (x *SyncRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SyncRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,2,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	ChunksCount   int32                  `protobuf:"varint,3,opt,name=chunks_count,json=chunksCount,proto3" json:"chunks_count,omitempty"`
	PageCount     int32                  `protobuf:"varint,4,opt,name=page_count,json=pageCount,proto3" json:"page_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_runtime_v1_runtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_api_runtime_v1_runtime_proto_rawDescGZIP(), []int{6}
}

func (x *SyncResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncResponse) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *SyncResponse) GetChunksCount() int32 {
	if x != nil {
		return x.ChunksCount
	}
	return 0
}

func (x *SyncResponse) GetPageCount() int32 {
	if x != nil {
		return x.PageCount
	}
	return 0
}

var File_api_runtime_v1_runtime_proto protoreflect.FileDescriptor

const file_api_runtime_v1_runtime_proto_rawDesc = "" +
	"\n" +
	"\x1capi/runtime/v1/runtime.proto\x12\n" +
	"chimera.v1\"\xb4\x01\n" +
	"\x0fRunAgentRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12&\n" +
	"\x0fapp_config_json\x18\x04 \x01(\tR\rappConfigJson\x12-\n" +
	"\ahistory\x18\x05 \x03(\v2\x13.chimera.v1.MessageR\ahistory\"7\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x9d\x01\n" +
	"\x10RunAgentResponse\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12)\n" +
	"\x04meta\x18\x03 \x01(\v2\x15.chimera.v1.AgentMetaR\x04meta\x120\n" +
	"\asummary\x18\x04 \x01(\v2\x16.chimera.v1.RunSummaryR\asummary\"d\n" +
	"\tAgentMeta\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x03R\n" +
	"durationMs\"\xd0\x01\n" +
	"\n" +
	"RunSummary\x12!\n" +
	"\ftotal_tokens\x18\x01 \x01(\x05R\vtotalTokens\x12#\n" +
	"\rprompt_tokens\x18\x02 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x03 \x01(\x05R\x10completionTokens\x12*\n" +
	"\x11total_duration_ms\x18\x04 \x01(\x03R\x0ftotalDurationMs\x12!\n" +
	"\ffinal_status\x18\x05 \x01(\tR\vfinalStatus\"|\n" +
	"\vSyncRequest\x12\x13\n" +
	"\x05kb_id\x18\x01 \x01(\x03R\x04kbId\x12#\n" +
	"\rdatasource_id\x18\x02 \x01(\x03R\fdatasourceId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1f\n" +
	"\vconfig_json\x18\x04 \x01(\tR\n" +
	"configJson\"\x87\x01\n" +
	"\fSyncResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\terror_msg\x18\x02 \x01(\tR\berrorMsg\x12!\n" +
	"\fchunks_count\x18\x03 \x01(\x05R\vchunksCount\x12\x1d\n" +
	"\n" +
	"page_count\x18\x04 \x01(\x05R\tpageCount2\xa2\x01\n" +
	"\x0eRuntimeService\x12I\n" +
	"\bRunAgent\x12\x1b.chimera.v1.RunAgentRequest\x1a\x1c.chimera.v1.RunAgentResponse\"\x000\x01\x12E\n" +
	"\x0eSyncDataSource\x12\x17.chimera.v1.SyncRequest\x1a\x18.chimera.v1.SyncResponse\"\x00B\"Z Chimera/server/api/runtime/v1;v1b\x06proto3"

var (
	file_api_runtime_v1_runtime_proto_rawDescOnce sync.Once
	file_api_runtime_v1_runtime_proto_rawDescData []byte
)

func file_api_runtime_v1_runtime_proto_rawDescGZIP() []byte {
	file_api_runtime_v1_runtime_proto_rawDescOnce.Do(func() {
		file_api_runtime_v1_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_runtime_v1_runtime_proto_rawDesc), len(file_api_runtime_v1_runtime_proto_rawDesc)))
	})
	return file_api_runtime_v1_runtime_proto_rawDescData
}

var file_api_runtime_v1_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_runtime_v1_runtime_proto_goTypes = []any{
	(*RunAgentRequest)(nil),  // 0: chimera.v1.RunAgentRequest
	(*Message)(nil),          // 1: chimera.v1.Message
	(*RunAgentResponse)(nil), // 2: chimera.v1.RunAgentResponse
	(*AgentMeta)(nil),        // 3: chimera.v1.AgentMeta
	(*RunSummary)(nil),       // 4: chimera.v1.RunSummary
	(*SyncRequest)(nil),      // 5: chimera.v1.SyncRequest
	(*SyncResponse)(nil),     // 6: chimera.v1.SyncResponse
}
var file_api_runtime_v1_runtime_proto_depIdxs = []int32{
	1, // 0: chimera.v1.RunAgentRequest.history:type_name -> chimera.v1.Message
	3, // 1: chimera.v1.RunAgentResponse.meta:type_name -> chimera.v1.AgentMeta
	4, // 2: chimera.v1.RunAgentResponse.summary:type_name -> chimera.v1.RunSummary
	0, // 3: chimera.v1.RuntimeService.RunAgent:input_type -> chimera.v1.RunAgentRequest
	5, // 4: chimera.v1.RuntimeService.SyncDataSource:input_type -> chimera.v1.SyncRequest
	2, // 5: chimera.v1.RuntimeService.RunAgent:output_type -> chimera.v1.RunAgentResponse
	6, // 6: chimera.v1.RuntimeService.SyncDataSource:output_type -> chimera.v1.SyncResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_runtime_v1_runtime_proto_init() }
func file_api_runtime_v1_runtime_proto_init() {
	if File_api_runtime_v1_runtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_runtime_v1_runtime_proto_rawDesc), len(file_api_runtime_v1_runtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_runtime_v1_runtime_proto_goTypes,
		DependencyIndexes: file_api_runtime_v1_runtime_proto_depIdxs,
		MessageInfos:      file_api_runtime_v1_runtime_proto_msgTypes,
	}.Build()
	File_api_runtime_v1_runtime_proto = out.File
	file_api_runtime_v1_runtime_proto_goTypes = nil
	file_api_runtime_v1_runtime_proto_depIdxs = nil
}
