// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: api/proto/rag_service.proto

package ragv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`                           // 用户问题
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`  // 会话ID (用于多轮对话记忆)
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`           // 租户隔离
	UseSearch     bool                   `protobuf:"varint,4,opt,name=use_search,json=useSearch,proto3" json:"use_search,omitempty"` // 是否开启联网/混合检索
	UseGraph      bool                   `protobuf:"varint,5,opt,name=use_graph,json=useGraph,proto3" json:"use_graph,omitempty"`    // 是否开启图谱增强
	ImageUrl      string                 `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`     // 用户上传的图片 URL，可选
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskRequest) Reset() {
	*x = AskRequest{}
	mi := &file_api_proto_rag_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskRequest) ProtoMessage() {}

func (x *AskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskRequest.ProtoReflect.Descriptor instead.
func (*AskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_service_proto_rawDescGZIP(), []int{0}
}

func (x *AskRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *AskRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AskRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AskRequest) GetUseSearch() bool {
	if x != nil {
		return x.UseSearch
	}
	return false
}

func (x *AskRequest) GetUseGraph() bool {
	if x != nil {
		return x.UseGraph
	}
	return false
}

func (x *AskRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type AskResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 两个字段可能不同时返回
	AnswerDelta string `protobuf:"bytes,1,opt,name=answer_delta,json=answerDelta,proto3" json:"answer_delta,omitempty"` // LLM 生成的正文片段 (流式吐字)
	ThinkingLog string `protobuf:"bytes,2,opt,name=thinking_log,json=thinkingLog,proto3" json:"thinking_log,omitempty"` // 思维链日志
	// 结构化引用来源 (前端展示用)
	SourceDocs    []*Reference `protobuf:"bytes,3,rep,name=source_docs,json=sourceDocs,proto3" json:"source_docs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskResponse) Reset() {
	*x = AskResponse{}
	mi := &file_api_proto_rag_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskResponse) ProtoMessage() {}

func (x *AskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskResponse.ProtoReflect.Descriptor instead.
func (*AskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_service_proto_rawDescGZIP(), []int{1}
}

func (x *AskResponse) GetAnswerDelta() string {
	if x != nil {
		return x.AnswerDelta
	}
	return ""
}

func (x *AskResponse) GetThinkingLog() string {
	if x != nil {
		return x.ThinkingLog
	}
	return ""
}

func (x *AskResponse) GetSourceDocs() []*Reference {
	if x != nil {
		return x.SourceDocs
	}
	return nil
}

type Reference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocName       string                 `protobuf:"bytes,1,opt,name=doc_name,json=docName,proto3" json:"doc_name,omitempty"` // 文档名
	PageNum       string                 `protobuf:"bytes,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"` // 页码
	Score         float32                `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`                  // 相关度分数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reference) Reset() {
	*x = Reference{}
	mi := &file_api_proto_rag_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reference) ProtoMessage() {}

func (x *Reference) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reference.ProtoReflect.Descriptor instead.
func (*Reference) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_service_proto_rawDescGZIP(), []int{2}
}

func (x *Reference) GetDocName() string {
	if x != nil {
		return x.DocName
	}
	return ""
}

func (x *Reference) GetPageNum() string {
	if x != nil {
		return x.PageNum
	}
	return ""
}

func (x *Reference) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type EmbedRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*EmbedRequest_Text
	//	*EmbedRequest_ImageUrl
	Data          isEmbedRequest_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedRequest) Reset() {
	*x = EmbedRequest{}
	mi := &file_api_proto_rag_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedRequest) ProtoMessage() {}

func (x *EmbedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedRequest.ProtoReflect.Descriptor instead.
func (*EmbedRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_service_proto_rawDescGZIP(), []int{3}
}

func (x *EmbedRequest) GetData() isEmbedRequest_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *EmbedRequest) GetText() string {
	if x != nil {
		if x, ok := x.Data.(*EmbedRequest_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *EmbedRequest) GetImageUrl() string {
	if x != nil {
		if x, ok := x.Data.(*EmbedRequest_ImageUrl); ok {
			return x.ImageUrl
		}
	}
	return ""
}

type isEmbedRequest_Data interface {
	isEmbedRequest_Data()
}

type EmbedRequest_Text struct {
	Text string `protobuf:"bytes,1,opt,name=text,proto3,oneof"` // 需要向量化的文本
}

type EmbedRequest_ImageUrl struct {
	ImageUrl string `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3,oneof"` // 需要向量化的图片
}

func (*EmbedRequest_Text) isEmbedRequest_Data() {}

func (*EmbedRequest_ImageUrl) isEmbedRequest_Data() {}

type EmbedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        []float32              `protobuf:"fixed32,1,rep,packed,name=vector,proto3" json:"vector,omitempty"` // 返回 768 或 1024 维向量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedResponse) Reset() {
	*x = EmbedResponse{}
	mi := &file_api_proto_rag_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedResponse) ProtoMessage() {}

func (x *EmbedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_rag_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedResponse.ProtoReflect.Descriptor instead.
func (*EmbedResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rag_service_proto_rawDescGZIP(), []int{4}
}

func (x *EmbedResponse) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

var File_api_proto_rag_service_proto protoreflect.FileDescriptor

const file_api_proto_rag_service_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/rag_service.proto\x12\x06rag.v1\"\xb3\x01\n" +
	"\n" +
	"AskRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"use_search\x18\x04 \x01(\bR\tuseSearch\x12\x1b\n" +
	"\tuse_graph\x18\x05 \x01(\bR\buseGraph\x12\x1b\n" +
	"\timage_url\x18\x06 \x01(\tR\bimageUrl\"\x87\x01\n" +
	"\vAskResponse\x12!\n" +
	"\fanswer_delta\x18\x01 \x01(\tR\vanswerDelta\x12!\n" +
	"\fthinking_log\x18\x02 \x01(\tR\vthinkingLog\x122\n" +
	"\vsource_docs\x18\x03 \x03(\v2\x11.rag.v1.ReferenceR\n" +
	"sourceDocs\"W\n" +
	"\tReference\x12\x19\n" +
	"\bdoc_name\x18\x01 \x01(\tR\adocName\x12\x19\n" +
	"\bpage_num\x18\x02 \x01(\tR\apageNum\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x02R\x05score\"K\n" +
	"\fEmbedRequest\x12\x14\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x12\x1d\n" +
	"\timage_url\x18\x02 \x01(\tH\x00R\bimageUrlB\x06\n" +
	"\x04data\"'\n" +
	"\rEmbedResponse\x12\x16\n" +
	"\x06vector\x18\x01 \x03(\x02R\x06vector2~\n" +
	"\n" +
	"LLMService\x126\n" +
	"\tAskStream\x12\x12.rag.v1.AskRequest\x1a\x13.rag.v1.AskResponse0\x01\x128\n" +
	"\tEmbedData\x12\x14.rag.v1.EmbedRequest\x1a\x15.rag.v1.EmbedResponseB\x12Z\x10api/rag/v1;ragv1b\x06proto3"

var (
	file_api_proto_rag_service_proto_rawDescOnce sync.Once
	file_api_proto_rag_service_proto_rawDescData []byte
)

func file_api_proto_rag_service_proto_rawDescGZIP() []byte {
	file_api_proto_rag_service_proto_rawDescOnce.Do(func() {
		file_api_proto_rag_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rag_service_proto_rawDesc), len(file_api_proto_rag_service_proto_rawDesc)))
	})
	return file_api_proto_rag_service_proto_rawDescData
}

var file_api_proto_rag_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_rag_service_proto_goTypes = []any{
	(*AskRequest)(nil),    // 0: rag.v1.AskRequest
	(*AskResponse)(nil),   // 1: rag.v1.AskResponse
	(*Reference)(nil),     // 2: rag.v1.Reference
	(*EmbedRequest)(nil),  // 3: rag.v1.EmbedRequest
	(*EmbedResponse)(nil), // 4: rag.v1.EmbedResponse
}
var file_api_proto_rag_service_proto_depIdxs = []int32{
	2, // 0: rag.v1.AskResponse.source_docs:type_name -> rag.v1.Reference
	0, // 1: rag.v1.LLMService.AskStream:input_type -> rag.v1.AskRequest
	3, // 2: rag.v1.LLMService.EmbedData:input_type -> rag.v1.EmbedRequest
	1, // 3: rag.v1.LLMService.AskStream:output_type -> rag.v1.AskResponse
	4, // 4: rag.v1.LLMService.EmbedData:output_type -> rag.v1.EmbedResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_rag_service_proto_init() }
func file_api_proto_rag_service_proto_init() {
	if File_api_proto_rag_service_proto != nil {
		return
	}
	file_api_proto_rag_service_proto_msgTypes[3].OneofWrappers = []any{
		(*EmbedRequest_Text)(nil),
		(*EmbedRequest_ImageUrl)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rag_service_proto_rawDesc), len(file_api_proto_rag_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_rag_service_proto_goTypes,
		DependencyIndexes: file_api_proto_rag_service_proto_depIdxs,
		MessageInfos:      file_api_proto_rag_service_proto_msgTypes,
	}.Build()
	File_api_proto_rag_service_proto = out.File
	file_api_proto_rag_service_proto_goTypes = nil
	file_api_proto_rag_service_proto_depIdxs = nil
}
