# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rag.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rag.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trag.proto\x12\x06rag.v1\"q\n\x0b\x43hatRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x0e\n\x06org_id\x18\x03 \x01(\x03\x12\r\n\x05kb_id\x18\x04 \x01(\x03\x12 \n\x07history\x18\x05 \x03(\x0b\x32\x0f.rag.v1.Message\"(\n\x07Message\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"6\n\tChatReply\x12\x14\n\x0c\x61nswer_delta\x18\x01 \x01(\t\x12\x13\n\x0bsource_docs\x18\x02 \x01(\t\"f\n\x0cParseRequest\x12\x14\n\x0cstorage_path\x18\x01 \x01(\t\x12\x11\n\tfile_name\x18\x02 \x01(\t\x12\r\n\x05kb_id\x18\x03 \x01(\x03\x12\x0e\n\x06\x64oc_id\x18\x04 \x01(\x03\x12\x0e\n\x06org_id\x18\x05 \x01(\x03\"q\n\rParseResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\terror_msg\x18\x02 \x01(\t\x12\x13\n\x0b\x63hunk_count\x18\x03 \x01(\x05\x12\x12\n\npage_count\x18\x04 \x01(\x05\x12\x13\n\x0btoken_usage\x18\x05 \x01(\x05\x32\x87\x01\n\nRagService\x12\x38\n\nChatStream\x12\x13.rag.v1.ChatRequest\x1a\x11.rag.v1.ChatReply\"\x00\x30\x01\x12?\n\x0eParseAndIngest\x12\x14.rag.v1.ParseRequest\x1a\x15.rag.v1.ParseResponse\"\x00\x42\x1bZ\x19\x43himera-RAG/api/rag/v1;v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rag_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\031Chimera-RAG/api/rag/v1;v1'
  _globals['_CHATREQUEST']._serialized_start=21
  _globals['_CHATREQUEST']._serialized_end=134
  _globals['_MESSAGE']._serialized_start=136
  _globals['_MESSAGE']._serialized_end=176
  _globals['_CHATREPLY']._serialized_start=178
  _globals['_CHATREPLY']._serialized_end=232
  _globals['_PARSEREQUEST']._serialized_start=234
  _globals['_PARSEREQUEST']._serialized_end=336
  _globals['_PARSERESPONSE']._serialized_start=338
  _globals['_PARSERESPONSE']._serialized_end=451
  _globals['_RAGSERVICE']._serialized_start=454
  _globals['_RAGSERVICE']._serialized_end=589
# @@protoc_insertion_point(module_scope)
