# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import rag_pb2 as rag__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rag_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RagServiceStub(object):
    """定义 RAG 核心服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChatStream = channel.unary_stream(
                '/rag.v1.RagService/ChatStream',
                request_serializer=rag__pb2.ChatRequest.SerializeToString,
                response_deserializer=rag__pb2.ChatReply.FromString,
                _registered_method=True)
        self.ParseAndIngest = channel.unary_unary(
                '/rag.v1.RagService/ParseAndIngest',
                request_serializer=rag__pb2.ParseRequest.SerializeToString,
                response_deserializer=rag__pb2.ParseResponse.FromString,
                _registered_method=True)


class RagServiceServicer(object):
    """定义 RAG 核心服务
    """

    def ChatStream(self, request, context):
        """1. 聊天接口 (流式)
        v0.4.0 变更: 请求中需要携带 OrgID/KbID 以进行隔离检索
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ParseAndIngest(self, request, context):
        """2. 解析并入库接口
        v0.4.0 变更: 不再传文件流，而是传 MinIO 路径；不再返回向量，只返回统计信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RagServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChatStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ChatStream,
                    request_deserializer=rag__pb2.ChatRequest.FromString,
                    response_serializer=rag__pb2.ChatReply.SerializeToString,
            ),
            'ParseAndIngest': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseAndIngest,
                    request_deserializer=rag__pb2.ParseRequest.FromString,
                    response_serializer=rag__pb2.ParseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rag.v1.RagService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rag.v1.RagService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RagService(object):
    """定义 RAG 核心服务
    """

    @staticmethod
    def ChatStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rag.v1.RagService/ChatStream',
            rag__pb2.ChatRequest.SerializeToString,
            rag__pb2.ChatReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ParseAndIngest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.v1.RagService/ParseAndIngest',
            rag__pb2.ParseRequest.SerializeToString,
            rag__pb2.ParseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
