# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: runtime.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'runtime.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rruntime.proto\x12\nchimera.v1\"\x83\x01\n\x0fRunAgentRequest\x12\x0e\n\x06\x61pp_id\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\x12\x12\n\nsession_id\x18\x03 \x01(\t\x12\x17\n\x0f\x61pp_config_json\x18\x04 \x01(\t\x12$\n\x07history\x18\x05 \x03(\x0b\x32\x13.chimera.v1.Message\"(\n\x07Message\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\x7f\n\x10RunAgentResponse\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\x12#\n\x04meta\x18\x03 \x01(\x0b\x32\x15.chimera.v1.AgentMeta\x12\'\n\x07summary\x18\x04 \x01(\x0b\x32\x16.chimera.v1.RunSummary\"E\n\tAgentMeta\x12\x11\n\tnode_name\x18\x01 \x01(\t\x12\x10\n\x08trace_id\x18\x02 \x01(\t\x12\x13\n\x0b\x64uration_ms\x18\x03 \x01(\x03\"\x85\x01\n\nRunSummary\x12\x14\n\x0ctotal_tokens\x18\x01 \x01(\x05\x12\x15\n\rprompt_tokens\x18\x02 \x01(\x05\x12\x19\n\x11\x63ompletion_tokens\x18\x03 \x01(\x05\x12\x19\n\x11total_duration_ms\x18\x04 \x01(\x03\x12\x14\n\x0c\x66inal_status\x18\x05 \x01(\t\"V\n\x0bSyncRequest\x12\r\n\x05kb_id\x18\x01 \x01(\x03\x12\x15\n\rdatasource_id\x18\x02 \x01(\x03\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x13\n\x0b\x63onfig_json\x18\x04 \x01(\t\"\\\n\x0cSyncResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\terror_msg\x18\x02 \x01(\t\x12\x14\n\x0c\x63hunks_count\x18\x03 \x01(\x05\x12\x12\n\npage_count\x18\x04 \x01(\x05\x32\xa2\x01\n\x0eRuntimeService\x12I\n\x08RunAgent\x12\x1b.chimera.v1.RunAgentRequest\x1a\x1c.chimera.v1.RunAgentResponse\"\x00\x30\x01\x12\x45\n\x0eSyncDataSource\x12\x17.chimera.v1.SyncRequest\x1a\x18.chimera.v1.SyncResponse\"\x00\x42*Z(Chimera-RAG/backend-go/api/runtime/v1;v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'runtime_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z(Chimera-RAG/backend-go/api/runtime/v1;v1'
  _globals['_RUNAGENTREQUEST']._serialized_start=30
  _globals['_RUNAGENTREQUEST']._serialized_end=161
  _globals['_MESSAGE']._serialized_start=163
  _globals['_MESSAGE']._serialized_end=203
  _globals['_RUNAGENTRESPONSE']._serialized_start=205
  _globals['_RUNAGENTRESPONSE']._serialized_end=332
  _globals['_AGENTMETA']._serialized_start=334
  _globals['_AGENTMETA']._serialized_end=403
  _globals['_RUNSUMMARY']._serialized_start=406
  _globals['_RUNSUMMARY']._serialized_end=539
  _globals['_SYNCREQUEST']._serialized_start=541
  _globals['_SYNCREQUEST']._serialized_end=627
  _globals['_SYNCRESPONSE']._serialized_start=629
  _globals['_SYNCRESPONSE']._serialized_end=721
  _globals['_RUNTIMESERVICE']._serialized_start=724
  _globals['_RUNTIMESERVICE']._serialized_end=886
# @@protoc_insertion_point(module_scope)
